language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "nightly"
- "pypy3"

# This dependency is only required for testing.
install:
- pip install PyHamcrest
- pip install Distance
script: python -m unittest
